name: Compile and release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Setup SourcePawn Compiler ${{ matrix.SM_VERSION }}
        id: setup_sp
        uses: rumblefrog/setup-sp@master
        with:
          version: "1.11.x"

      - name: Compile plugins
        run: |
          mkdir "addons/sourcemod/plugins/"
          spcomp -w234 -O2 -v2 -o"addons/sourcemod/plugins/dmspawns.smx" addons/sourcemod/scripting/dmspawns.sp
          echo "===OUT FILES==="
          ls "addons/sourcemod/plugins"
          echo "===VERSION==="
          echo ${{ steps.setup_sp.outputs.plugin-version }}

      - name: Changelog
        id: changelog
        uses: mindsers/changelog-reader-action@v2

      - name: Install zip
        uses: montudor/action-zip@v1
        
      - name: Create Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          artifacts: "addons/sourcemod/plugins/*.smx"
          body: ${{ steps.changelog.outputs.changes }}
          draft: false
          allowUpdates: true
          prerelease: false
          replacesArtifacts: true
