name: Test Sourcemod compilation

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set environment variables
        run: echo SCRIPTS_PATH=$(pwd) >> $GITHUB_ENV

      - name: Setup SourcePawn Compiler ${{ matrix.SM_VERSION }}
        id: setup_sp
        uses: rumblefrog/setup-sp@master
        with:
          version: "1.11.x"
          version-file: addons/sourcemod/scripting/dmspawns.sp

      - name: Compile plugins
        run: |
          mkdir ../plugins
          spcomp -w234 -O2 -v2 -o"addons/sourcemod/plugins/dmspawns.smx" addons/sourcemod/scripting/dmspawns.sp
          echo "===OUT FILES==="
          ls "addons/sourcemod/plugins/dmspawns.sp"
          echo "===VERSION==="
          echo ${{ steps.setup_sp.outputs.plugin-version }}
        working-directory: ${{ env.SCRIPTS_PATH }}/scripting
